version: '3.8'

services:

  back:
    container_name: ${IMAGE_NAME}-back
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    build:
      dockerfile: Dockerfile
      context: ./deploy
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    env_file:
      - ./.env
    volumes:
      - ./back:/app
      - ./logs:/logs
      # - ./deploy/gunicorn.py:/gunicorn.py
    working_dir: /app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 5000
    # command: gunicorn -c /gunicorn.py main:app
