version: "3.8"

volumes:
  db:
    driver: local

services:
  db:
    container_name: ${IMAGE_NAME}-db
    image: postgres:15
    restart: no
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: ["5432:5432"]
    volumes:
      - ./deploy/db_data:/var/lib/postgresql/data

  back:
    container_name: ${IMAGE_NAME}-back
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    build:
      dockerfile: Dockerfile
      context: ./deploy
      args:
        BASE_IMAGE: ${BASE_IMAGE}
    env_file:
      - ./.env
    volumes:
      - ./back:/app
      - ./logs:/logs
      # - ./deploy/gunicorn.py:/gunicorn.py
    ports: ["5000:5000"]
    working_dir: /app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 5000
    # command: gunicorn -c /gunicorn.py main:app

  front:
    container_name: ${IMAGE_NAME}-front
    image: node:18
    stdin_open: true
    # tty: true
    working_dir: /app
    volumes:
      - ./front:/app
    ports: ["3000:3000"]
    command: sleep infinity

#  nginx:
#    container_name: ${IMAGE_NAME}-nginx
#    image: nginx:stable
#    depends_on: [ back, front ]
#    ports: [ "5000:5000" ]
#    volumes:
#      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./deploy/nginx.dev:/etc/nginx/conf.d/default.conf:ro
#      - ./logs/nginx:/var/log/ngin
#      - ./media:/media
